version: "3.8"

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: "server -dev -dev-root-token-id=root"

  vault-agent:
    image: vault:1.13.3
    container_name: vault-agent
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - ./vault/templates:/vault/templates
      - ./vault/secrets:/vault/secrets
    depends_on:
      - vault
    command: "vault agent -config=/vault/config/config.hcl"

  app:
    build: .
    container_name: vault-test
    volumes:
      - ./vault/secrets:/vault/secrets
    depends_on:
      - vault-agent
